### ISSUE TITLE
tests fails when importing nfsft from pynfft

### ISSUE THREAD

**Issue by mariogeiger** [AMLab-Amsterdam/lie_learn#11]
The tests does not pass when I try to build the package in order to create a conda-forge repository:
https://github.com/conda-forge/staged-recipes/pull/10861

I get the following error:
[`ImportError: cannot import name 'nfsft' from 'pynfft' ($PREFIX/lib/python3.7/site-packages/pynfft/__init__.py)`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=123814&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=987)

**Comment by bkmi** [comment]
The reason is that [the package](https://github.com/pyNFFT/pyNFFT) is not listed in requirements and (after trying to add it to requirements) is semi-complicated to install.

Is it possible to remove this test case?

**Comment by bkmi** [comment]
However there are other failing test cases... 

lie_learn/spectral/tests/test_SO3_FFT_Naive.py:112: AssertionError
lie_learn/spectral/tests/test_SO3_FFT_Naive.py:157: AssertionError
