### ISSUE TITLE
No module named 'lie_learn.representations.SO3.irrep_bases'

### ISSUE THREAD

**Issue by Syhzs** [AMLab-Amsterdam/lie_learn#16]
I failed import this .c file . I have a c compile(vs c++ 2015) and already pip install cython.( python 3.6 ,pytorch 1.1.0 cuda 9.0)

**Comment by Linh-nk** [comment]
I also ran into this error

**Comment by vwslz** [comment]
Same error here: ModuleNotFoundError: No module named 'lie_learn.representations.SO3.irrep_bases'

**Comment by HannesStark** [comment]
You might want to try:

pip install git+https://github.com/AMLab-Amsterdam/lie_learn

for me this did not work either and was running into a cython issue but installing an older commit worked:

pip install git+https://github.com/AMLab-Amsterdam/lie_learn@6d02c2a1705a05340a128cb8d86c19076d0f5f46

**Comment by EricPengShuai** [comment]
@HannesStark 
lie_learn cannot be installed using these two commands. My environment is anaconda with pytorch1.8 and python3.7.
https://github.com/AMLab-Amsterdam/lie_learn/issues/20#issue-960044662

**Comment by jk160804211** [comment]
probably, you need to download the whole project and use setup.py file to install using the command `python  setup.py install`
personally, the setup.py has problem leading the Cpython report the compile error "is not a valid module name", I modified the code of setup.py in line 29 `extensions = cythonize(extensions)` to `extensions = cythonize(files)`, and it works.

**Comment by chinkihamza** [comment]
from lie_learn.representations.SO3.irrep_bases import change_of_basis_matrix
      8 def wigner_d_matrix(l, beta,
      9                     field='real', normalization='quantum', order='centered', condon_shortley='cs'):
     10     """
     11     Compute the Wigner-d matrix of degree l at beta, in the basis defined by
     12     (field, normalization, order, condon_shortley)
   (...)
     22     :return: d^l_mn(beta) in the chosen basis
     23     """

ModuleNotFoundError: No module named 'lie_learn.representations.SO3.irrep_bases'

**Comment by 1597446909** [comment]
I have solved this problem.
at first,you should run "pip  install cpython","pip install easycpython",and then go to the pakage root,"pip install . "。
then ,you enter the .\representations\SO3,and will find the irrep_bases.pyx and the irrep_bases.c。
at least ,open the cmd in this dir,run "easycpython irrep_bases.pyx"，after that,you will find a pyd file，that is over.
