### ISSUE TITLE
Can you help me download J_dense_0-278.npy file?

### ISSUE THREAD

**Issue by MasonSuWei** [AMLab-Amsterdam/lie_learn#3]
Hi,

I am trying to test s2cnn, it is a great algorith.

But I can't download J_dense_0-278.npy. Is there another way to get this file?

Mason Su
Best regards

**Comment by MasonSuWei** [comment]
Hi,

I found a way to download the file.

**Comment by silent-wn** [comment]
How can I download this file?When I download,the page can't be linked

**Comment by silent-wn** [comment]
> Hi,
> 
> I found a way to download the file.

Could you sent this file to me?my email is wn172585288@gmail.com.Thank you very much!

**Comment by tscohen** [comment]
You can download it here: https://drive.google.com/open?id=0B5e7DAOiLEZwSkdfXzBYT29Nc3c
